[package]
name = "regal-examples"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies]
regal = { path = "../regal" }
regal-macros = { path = "../regal-macros" }
ariadne.workspace = true
chumsky.workspace = true
cursive.workspace = true
