[package]
name = "regal-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
regex-syntax = "0.8"
syn = { version = "2", features = ["full"] }
regal = { path = ".." }
