[package]
name = "regal"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
heapless.workspace = true

[dev-dependencies]
regal-macros = { path = "../regal-macros" }
